general_skills_list = [
    "Communication",
    "Problem Solving",
    "Teamwork",
    "Time Management",
    "Adaptability",
    "Critical Thinking",
    "Attention to Detail",
    "Collaboration",
    "Customer-Focused",
    "Project Management",
    "Leadership",
    "Creativity",
    "creative",
    "Analytical",
    "Self-Motivation",
    "Conflict Resolution",
    "Multitasking",
    "Research",
    "Decision Making",
    "Interpersonal",
    "Negotiation",
    "Flexibility",
    "Conflict Management",
    "Organization",
    "Emotional Intelligence",
    "Stakeholder Management",
    "Critical Feedback",
    "Client Relations",
    "Work Under Pressure",
    "fast pace",
    "Networking",
    "Agile",
    "scrum",
    "Remote Work",
    "Slack",
    "Conflict Management",
    "Business Acumen",
    "Self-Discipline",
    "Resourceful",
    "Proactive",
    "Leadership",
    "Productivity Tools",
    "Trello",
    "confluence",
    "jira",
    "Presentation",
    "Strategic Thinking",
    "Research",
    "Analysis",
    "Mentoring Juniors",
    "Quality Assurance",
    "Continuous Improvement",
    "Data Analysis",
    "Documentation",
    "Training & Development",
    "Empathy",
    "Client Management",
    "Customer Support",
    "debugging",
    "code review",
    "deployment",
    "support tickets",
    "pair programming",
    "scoping",
    "banking",
    "finance",
    "blockchain",
    "client facing"
]
