skills_list = [
    "Python",
    "Java",
    "TypeScript",
    "Ruby",
    "Machine Learning",
    "NLP",
    "Tableau",
    "PowerBI",
    "TensorFlow",
    "Docker",
    "Spring Boot",
    "REST API",
    "React",
    "Ruby on Rails",
    "Javascript",
    "Jest",
    "playwright",
    "vitest",
    "unittest",
    "pytest",
    "nose2",
    "doctest",
    "Mocha",
    "Chai",
    "Jasmine",
    "Ava",
    "Cypress",
    "Enzyme",
    "RSpec",
    "Minitest",
    "Cucumber",
    "Capybara",
    "FactoryBot",
    "JUnit",
    "TestNG",
    "Mockito",
    "Spock",
    "NUnit",
    "xUnit",
    "MSTest",
    "Moq",
    "PHPUnit",
    "Behat",
    "Codeception",
    "testing",
    "Ginkgo",
    "GoMock",
    "XCTest",
    "Quick",
    "Nimble",
    "Spek",
    "MockK",
    "Selenium",
    "Puppeteer",
    "Sinatra",
    "ActiveRecord",
    "Sidekiq",
    "Postgres",
    "MySQL",
    "Redis",
    "PostgreSQL",
    "RubyGems",
    "Bundler",
    "Devise",
    "Pundit",
    "ActionCable",
    "Webpacker",
    "Turbo",
    "Stimulus",
    "Hotwire",
    "RESTful APIs",
    "GraphQL",
    "Kubernetes",
    "CI/CD",
    "CI",
    "Continuous integration",
    "GitHub Actions",
    "CircleCI",
    "Jenkins",
    "AWS",
    "TDD",
    "BDD",
    "MVC",
    "GitHub",
    "GIT",
    "Elasticsearch",
    "Nginx",
    "Puma",
    "Rake",
    "Rubocop",
    "Haml",
    "SCSS",
    "JBuilder",
    "ActiveJob",
    "ActionMailer",
    "WebSockets",
    "Spina CMS",
    "RefineryCMS",
    "Pusher",
    "Capistrano",
    "Heroku",
    "ES6",
    "Node.js",
    "Express.js",
    "Vue.js",
    "Angular",
    "Redux",
    "Webpack",
    "Babel",
    "NPM",
    "Yarn",
    "Ajax",
    "Fetch API",
    "D3.js",
    "Three.js",
    "HTML5",
    "CSS3",
    "Bootstrap",
    "Tailwind CSS",
    "jQuery",
    "ES Modules",
    "WebRTC",
    "Next.js",
    "Gatsby",
    "Electron",
    "Socket.io",
    "PWA",
    "Service Workers",
    "Lodash",
    "Moment.js",
    "Testing Library",
    "Firebase",
    "GraphQL (Apollo Client)",
    "MongoDB",
    "Django",
    "Flask",
    "FastAPI",
    "Pyramid",
    "SQLAlchemy",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Keras",
    "PyTorch",
    "Scikit-learn",
    "Jupyter Notebooks",
    "Celery",
    "Sphinx",
    "Pytest-Django",
    "BeautifulSoup",
    "Scrapy",
    "Requests",
    "Pylint",
    "Flake8",
    "Boto3",
    "Google Cloud SDK",
    "Azure SDK",
    "OpenCV",
    "Plotly",
    "Dash",
    "NLTK",
    "spaCy",
    "Tesseract",
    "PyGame",
    "Twisted",
    "asyncio",
    "Flask-RESTful",
    "C#",
    ".NET",
    "ASP.NET Core",
    "ASP.NET MVC",
    "Entity Framework",
    "LINQ",
    "SQL Server",
    "Xamarin",
    "Blazor",
    "WPF",
    "WinForms",
    "SignalR",
    "Azure",
    "NUnit",
    "MSTest",
    "xUnit",
    "Razor Pages",
    "Web API",
    "Microservices",
    "T-SQL",
    "Visual Studio",
    "Dependency Injection",
    "Windows Services",
    "WCF (Windows Communication Foundation)",
    ".NET MAUI",
    "IdentityServer",
    "NHibernate",
    "LINQPad",
    "Kafka",
    "ELK Stack",
    "Apache Kafka",
    "Apache Camel",
    "JMS",
    "Mockito",
    "TestNG",
    "Log4j",
    "SLF4J",
    "Java Streams API",
    "Lambda Expressions",
    "Multithreading",
    "Concurrency",
    "JDBC",
    "Spring Framework",
    "Spring Boot",
    "Hibernate",
    "Java EE",
    "JPA",
    "Spring MVC",
    "Spring Security",
    "Spring Cloud",
    "SOAP Web Services",
    "JavaFX",
    "JSP",
    "Servlets",
    "Maven",
    "Gradle",
    "JUnit",
    "Mockito",
    "TestNG",
    "Log4j",
    "SLF4J",
    "Java Streams API",
    "Lambda Expressions",
    "Multithreading",
    "Concurrency",
    "JDBC",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Spring Data",
    "Apache Tomcat",
    "JBoss/WildFly",
    "RabbitMQ",
    "Eclipse/IntelliJ IDEA",
    "Apache Hadoop",
    "Golang",
    "Go Concurrency",
    "Go Standard",
    "Gin",
    "Echo",
    "gRPC",
    "Protocol Buffers",
    "GoCD",
    "GoDoc",
    "Prometheus",
    "Go-Metrics",
    "NATS Messaging",
    "WebSockets",
    "Go routines and Channels",
    "RESTful Services",
    "Proxies",
    "Helm Charts",
    "GoReleaser",
    "Performance Optimization",
    "Binaries Deployment",
    "Dependency Injection",
    "Microsoft SQL Server",
    "Oracle",
    "MariaDB",
    "IBM Db2",
    "Amazon RDS",
    "Cassandra",
    "CouchDB",
    "Firebase",
    "DynamoDB",
    "Apache",
    "RavenDB",
    "Neo4j",
    "ArangoDB",
    "Amazon DocumentDB",
    "Couchbase",
    "InfluxDB",
    "TimescaleDB",
    "Prometheus",
    "OpenTSDB",
    "Google Spanner",
    "CockroachDB",
    "VoltDB",
    "Apache HBase",
    "Amazon Redshift",
    "ClickHouse",
    "Google BigQuery",
    "Snowflake",
    "Microsoft Azure Synapse Analytics",
    "JSON"
]
